
services:
  aihawk-app:
    build: .
    ports:
      - "${PORT:-8501}:${PORT:-8501}"
    volumes:
      - ./data_folder:/app/data_folder
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=${PORT:-8501}
    shm_size: "1gb"
    restart: unless-stopped
