remote: true

experienceLevel:
  internship: false
  entry: true
  associate: true
  mid-senior level: true
  director: false
  executive: false

jobTypes:
  full-time: true
  contract: false
  part-time: false
  temporary: true
  internship: false
  other: false
  volunteer: true

date:
  all time: false
  month: false
  week: false
  24 hours: true

positions:
  - IT
  - Computer Science
  - Web Design
  - Full Stack Developer

locations:
  - Afghanistan
  - Kabul

apply_once_at_company: true

distance: 100

company_blacklist:
  - wayfair
  - Crossover

title_blacklist:
  - word1
  - word2

job_applicants_threshold:
  min_applicants: 0
  max_applicants: 30

llm_model_type: openai
llm_model: 'gpt-4o-mini'
